name: shop_example
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  ionicons: ^0.2.2
  google_fonts: ^5.1.0
  iconsax: ^0.0.8
  firebase_core: ^2.24.2
  firebase_ui_auth: ^1.10.0
  provider: ^6.1.1
  cloud_firestore: ^4.13.6
  image_picker: ^1.0.6
  firebase_storage: ^11.6.0
  firebase_app_check: ^0.2.1+8
  flutter_credit_card: ^4.0.1
  patterns_canvas: ^0.4.0
  flip_card: ^0.7.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - google_fonts/
    - assets/images/
    - assets/icons/
    - assets/logos/
